name: Clean EPG Files

on:
  schedule:
    # Runs at 23:55 Auckland time (UTC+12 or UTC+13)
    # For UTC+12 (non-DST): 11:55 UTC same day
    # For UTC+13 (DST): 10:55 UTC same day
    - cron: '55 12 * * *'  # 1:00 AM AKL time
  workflow_dispatch: # Allows manual triggering

jobs:
  clean-epg-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Delete old EPG files
      run: |
        # List of files to delete
        files=("public/epg.xml" "public/epg.xml.gz" "public/lk.xml" "public/si.xml")
        
        # Delete each file if it exists
        for file in "${files[@]}"; do
          if [ -f "$file" ]; then
            echo "Deleting $file"
            rm -v "$file"
          else
            echo "$file not found"
          fi
        done

    - name: Commit and push changes
      if: always()
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Check if any of our target files were deleted
        if git ls-files --deleted | grep -q -E 'public/(epg.xml|epg.xml.gz|lk.xml|si.xml)'; then
          git add -u public/ # Stage deletions
          git commit -m "Cleanup old EPG files [$(date +'%Y-%m-%d %H:%M:%S')]"
          git pull --rebase origin main
          git push origin main
          echo "File deletions committed"
        else
          echo "No target files found to delete"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
