name: Extract EPG File

on:
  schedule:
    - cron: "30 12 * * *" # Runs daily at 00:30 AKL (12:30 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  extract-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Required Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip

    - name: Extract EPG File
      run: |
        python3 extract_epg.py

    - name: Commit and Push Extracted File
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add public/epg.xml
        git commit -m "Update extracted epg.xml file" --allow-empty
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
