name: Generate Sri Lanka EPG

on:
  schedule:
    - cron: "30 0 * * *"  # Runs at 12:30 AM UTC (12:30 PM AKL)
  workflow_dispatch:

jobs:
  generate-lk-epg:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils xmlstarlet
        pip install defusedxml

    - name: Ensure public directory exists
      run: mkdir -p public

    - name: Verify Input File
      run: |
        if [ -f "public/epg.xml" ]; then
          echo "Input file exists"
          echo "First 20 lines:"
          head -n 20 public/epg.xml
        else
          echo "Error: Input file not found"
          exit 1
        fi

    - name: Run EPG Filter
      run: python3 generate_lk.py -i public/epg.xml -o public/lk.xml

    - name: Verify Output
      run: |
        if [ -f "public/lk.xml" ]; then
          echo "Output file created successfully"
          echo "First 20 lines:"
          head -n 20 public/lk.xml
          echo "Total channels found: $(grep -c '<channel' public/lk.xml)"
        else
          echo "Error: Output file not created"
          exit 1
        fi

    - name: Upload Output
      uses: actions/upload-artifact@v3
      with:
        name: sri-lanka-epg
        path: public/lk.xml
