name: Generate Dialog XML

on:
  schedule:
    - cron: "15 13 * * *" # Runs daily at 01:15 AKL (13:15 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-dialog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Required Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y python3

    - name: Generate Dialog XML
      run: |
        python3 generate_dialog.py

    - name: Commit and Push Dialog File
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add public/dialog.xml
        git commit -m "Update dialog.xml file" --allow-empty
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
