name: Generate and Publish LK EPG

on:
  schedule:
    - cron: "30 0 * * *"  # 12:30 PM NZT daily
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils xmlstarlet
        pip install defusedxml

    - name: Download EPG File
      run: |
        mkdir -p public
        curl -L "https://example.com/epg.xml" -o public/epg.xml

    - name: Run EPG Filter
      run: python3 generate_lk.py

    - name: Prepare GitHub Pages Content
      run: |
        mkdir -p output
        cp public/lk.xml output/lk.xml
        touch output/.nojekyll

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
