name: Generate Sri Lanka EPG

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  generate-lk-epg:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils xmlstarlet
        pip install defusedxml requests

    - name: Create public directory
      run: mkdir -p public

    - name: Run EPG Filter
      run: |
        python3 generate_lk.py \
          -i "https://raw.githubusercontent.com/anilwee/dialog/main/public/epg.xml" \
          -o "public/lk.xml"

    - name: Verify Output
      run: |
        if [ -f "public/lk.xml" ]; then
          echo "EPG generated successfully"
          echo "Channels found: $(grep -c '<channel' public/lk.xml)"
        else
          echo "Error: Failed to generate EPG"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sri-lanka-epg
        path: public/lk.xml
