name: Generate Sinhala Translated EPG

on:
  schedule:
    - cron: "15 13 * * *" # Runs daily at 01:15 AKL (13:15 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-si:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Required Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install deep-translator

    - name: Generate Sinhala Translated EPG
      run: |
        python3 generate_si.py

    - name: Debug Generated Output
      run: |
        echo "Checking contents of the public directory..."
        ls -l public || echo "Public directory not found."

        echo "Checking if si.xml exists..."
        if [ -f public/si.xml ]; then
          echo "si.xml exists:"
          cat public/si.xml
        else:
          echo "Error: si.xml was not created!"
          exit 1
        fi

    - name: Commit and Push Translated File
      if: success()
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add public/si.xml
        git commit -m "Update Sinhala translated si.xml file"
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
