name: Generate and Host dialog.xml

on:
  push:
    branches:
      - main
  schedule:
    # Runs daily at 01:00 AKL (UTC+12 or UTC+13 during daylight savings)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-dialog-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests xmltodict

      - name: Generate dialog.xml
        run: python generate_dialog_xml.py

      - name: Debug: List public directory
        run: ls -l public || echo "No files found in public/ directory."

      - name: Debug: View dialog.xml
        if: success() && env.commit_changes == 'true'
        run: cat public/dialog.xml || echo "dialog.xml not created."

      - name: Check for changes
        id: check_changes
        run: |
        -run context=> create in env settings
Here is the corrected YAML workflow file and a simple explanation for its sections.
