name: VPN File Download

on:
  schedule:
    - cron: "0 12 * * *" # Runs daily at 00:00 AKL (12:00 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  vpn-download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install VPN and Required Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn wget

    - name: Connect to VPN and Download File
      run: |
        sudo openvpn --config "${{ secrets.VPN_CONFIG }}" --auth-user-pass <(echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}") &
        sleep 10 # Give VPN time to connect
        wget -O public/epg.xml.gz "https://remote-link-to-epg.xml.gz"

    - name: Commit and Push File
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add public/epg.xml.gz
        git commit -m "Update epg.xml.gz file" --allow-empty
        git pull --rebase origin main
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
