name: Generate SI XML

on:
  push:
    paths:
      - 'public/lk.xml'
      - '.github/workflows/translate_xml.yml'
      - 'translate_xml.py'
      - 'translation_mappings.yml'
  
  workflow_dispatch:
  schedule:
    - cron: '35 12,13 * * *'

jobs:
  generate-si-xml:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Strict timeout

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Cache dependencies

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run translation
        timeout-minutes: 1  # Hard timeout
        run: python translate_xml.py

      - name: Verify output
        run: |
          [ -f "public/si.xml" ] || exit 1
          echo "Generated file size: $(wc -c < public/si.xml) bytes"

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: generated-xml
          path: |
            public/si.xml
            .translation_cache.json
            translation_debug.log
