name: Daily XML Translation

on:
  schedule:
    - cron: '30 13 * * *'  # 1:30 AM AKL time
  workflow_dispatch:
  push:
    paths:
      - 'public/lk.xml'

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deep-translator pyyaml
        
    - name: Run translation script with debug
      run: |
        python translate_xml.py
        cat translation_debug.log
        
    - name: Verify output file
      run: |
        if [ -f "public/si.xml" ]; then
          echo "si.xml exists"
          ls -la public/
        else
          echo "si.xml was not created"
          exit 1
        fi
        
    - name: Commit and push changes
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add public/si.xml translation_debug.log
        git commit -m "Auto-update Sinhalese translation [skip ci]"
        git push
