name: Generate SI XML

on:
  push:
    paths:
      - 'public/lk.xml'
      - '.github/workflows/translate_xml.yml'
      - 'translate_xml.py'
  
  workflow_dispatch:
    inputs:
      source_file:
        description: 'Optional source file path'
        required: false
        default: 'public/lk.xml'

  schedule:
    - cron: '35 12,13 * * *'

jobs:
  generate-si-xml:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyyaml requests

      - name: Check for source file
        id: source-check
        run: |
          SOURCE="${{ github.event.inputs.source_file || 'public/lk.xml' }}"
          if [ -f "$SOURCE" ]; then
            echo "source_exists=true" >> $GITHUB_OUTPUT
            echo "source_path=$SOURCE" >> $GITHUB_OUTPUT
          else
            echo "source_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate/Translate XML
        run: |
          if ${{ steps.source-check.outputs.source_exists == 'true' }}; then
            echo "Translating program content (preserving channel names)..."
            python translate_xml.py \
              --input "${{ steps.source-check.outputs.source_path }}" \
              --output public/si.xml \
              --preserve-channels
          else
            echo "Generating new SI XML (English channel names)..."
            python -c "
import xml.etree.ElementTree as ET
root = ET.Element('tv')
# Channel with English name but Sinhala content
channel = ET.SubElement(root, 'channel', {'id': 'default'})
ET.SubElement(channel, 'display-name').text = 'English Channel'
ET.SubElement(channel, 'display-name', {'lang': 'si'}).text = 'සිංහල චැනල්'
# Sample program
program = ET.SubElement(root, 'programme', {'channel': 'default'})
ET.SubElement(program, 'title', {'lang': 'si'}).text = 'සිංහල වැඩසටහන'
ET.ElementTree(root).write('public/si.xml', encoding='utf-8', xml_declaration=True)
"
          fi

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/si.xml
          if ! git diff --cached --quiet; then
            git commit -m "Auto-generated SI XML [skip ci]"
            git push
          fi
