name: Translate LK XML to SI XML

on:
  push:
    paths:
      - 'public/lk.xml'
      - '.github/workflows/translate_xml.yml'
      - 'translate_xml.py'
  
  workflow_dispatch:  # Manual trigger
    inputs:
      force:
        description: 'Force update even if no changes detected'
        required: false
        default: 'false'

  schedule:
    # Runs daily at 01:35 AM Auckland time (UTC+12/+13)
    # Using 13:35 UTC (for UTC+12) and 12:35 UTC (for UTC+13 during DST)
    - cron: '35 12,13 * * *'

jobs:
  translate-xml:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hanging jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for proper git diff checking

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Run XML translation
        run: python translate_xml.py
        env:
          REQUEST_DELAY: 0.5
          FORCE_UPDATE: ${{ github.event_name == 'workflow_dispatch' && inputs.force == 'true' }}

      - name: Commit and push changes
        if: success() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || needs.check-changes.outputs.changed == 'true')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/si.xml
          git diff --cached --quiet && echo "No changes detected" || \
            (git commit -m "Auto-generated Sinhala XML [skip ci]" && git push)
