name: Generate SI XML

on:
  push:
    paths:
      - 'public/lk.xml'
      - '.github/workflows/translate_xml.yml'
      - 'translate_xml.py'
      - 'translation_mappings.yml'
  
  workflow_dispatch:
  schedule:
    - cron: '35 12,13 * * *'  # 1:35 AM Auckland Time (UTC+12/13)

jobs:
  generate-si-xml:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: ''  # Disables requirements.txt check

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Validate files
        run: |
          [ -f "public/lk.xml" ] || echo "::warning::lk.xml not found, will generate minimal file"
          [ -f "translation_mappings.yml" ] || echo "::warning::translation_mappings.yml missing"

      - name: Run XML translation
        id: translate
        run: python translate_xml.py
        timeout-minutes: 1

      - name: Verify output
        run: |
          if [ ! -f "public/si.xml" ]; then
            echo "::error::si.xml was not generated!"
            exit 1
          fi
          echo "Generated file size: $(wc -c < public/si.xml) bytes"

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: translation-debug
          path: |
            public/si.xml
            .translation_cache.json
            translation_debug.log
          retention-days: 2

      - name: Commit results
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/si.xml .translation_cache.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-updated SI XML [skip ci]"
            git push
          fi
