name: Generate SI XML

on:
  push:
    paths:
      - 'public/lk.xml'
      - '.github/workflows/translate_xml.yml'
      - 'translate_xml.py'
      - 'translation_mappings.yml'
  
  workflow_dispatch:
  schedule:
    - cron: '35 12,13 * * *'

jobs:
  generate-si-xml:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python (explicit)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: ''  # Disable auto requirements detection

      - name: Install dependencies (direct)
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run translation
        timeout-minutes: 1
        run: python translate_xml.py

      - name: Verify output
        run: |
          [ -f "public/si.xml" ] || { echo "::error::si.xml not generated!"; exit 1; }
          echo "Generated XML:"
          echo "Size: $(wc -c < public/si.xml) bytes"
          echo "First 3 lines:"
          head -n 3 public/si.xml

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xml-artifacts
          path: |
            public/si.xml
            .translation_cache.json
            translation_debug.log
          retention-days: 3

      - name: Commit results
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/si.xml .translation_cache.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-generated SI XML [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
