name: VPN Connect and File Host

on:
  schedule:
    - cron: '05 11,12 * * *'  # 00:05 Auckland time (accounts for DST)
  workflow_dispatch:

jobs:
  vpn-download-host:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up OpenVPN
      run: |
        # Create config from secret
        echo "${{ secrets.OVPN_FILE }}" | base64 -d > raw_config.ovpn
        fold -w 64 raw_config.ovpn > config.ovpn
        
        # Create auth file
        printf "%s\n" "${{ secrets.VPN_USERNAME }}" "${{ secrets.VPN_PASSWORD }}" > auth.txt
        chmod 600 auth.txt

        # Install OpenVPN
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Connect to VPN
      run: |
        sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
        sleep 15  # Give more time for connection to establish
        curl --max-time 10 https://ipinfo.io  # Verify connection

    - name: Download and Update EPG Files
      run: |
        # Download and process files
        wget -O epg.xml.gz https://watch.livecricketsl.xyz/epg/epg.xml.gz
        gunzip -c epg.xml.gz > epg.xml
        
        # Prepare public directory
        mkdir -p public
        rm -f public/epg.xml*
        mv epg.xml.gz public/
        mv epg.xml public/

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add public/
        
        # Only commit if there are changes
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Auto-update EPG files [$(date +'%Y-%m-%d %H:%M:%S')]"
          git pull --rebase origin main
          git push origin main
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup
      run: |
        sudo pkill openvpn || true
        rm -f config.ovpn raw_config.ovpn auth.txt
