name: VPN Connect Debug Workflow

on:
  workflow_dispatch:

jobs:
  debug-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Decode and Save OVPN Config
      run: |
        echo "${{ secrets.OVPN_FILE }}" | base64 -d > raw_config.ovpn
        fold -w 64 raw_config.ovpn > config.ovpn
        wc -L config.ovpn  # Check max line length to ensure it's under 256
        cat config.ovpn    # Optional: Inspect the config file for debugging

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn
        sudo openvpn --version

    - name: Create Auth File
      run: |
        printf "%s\n" "${{ secrets.VPN_USERNAME }}" "${{ secrets.VPN_PASSWORD }}" > auth.txt
        chmod 600 auth.txt  # Secure the file for OpenVPN usage
        cat auth.txt         # Optional: Verify contents for debugging (remove in production)

    - name: Sleep for Initialization
      run: sleep 5

    - name: Run OpenVPN Without Daemon
      run: |
        sudo openvpn --config config.ovpn --auth-user-pass auth.txt

    - name: Debug OpenVPN Logs
      run: |
        sudo cat /var/log/syslog | grep openvpn
