name: VPN Connect and File Host

on:
  schedule:
    - cron: '05 11,12 * * *'
  workflow_dispatch:

jobs:
  vpn-download-host:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Create .gitignore if it doesn't exist
    - name: Setup .gitignore
      run: |
        if [ ! -f .gitignore ]; then
          echo "config.ovpn" >> .gitignore
          echo "raw_config.ovpn" >> .gitignore
          echo "auth.txt" >> .gitignore
        fi

    - name: Decode and Save OVPN Config
      run: |
        echo "${{ secrets.OVPN_FILE }}" | base64 -d > raw_config.ovpn
        fold -w 64 raw_config.ovpn > config.ovpn

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Create Auth File
      run: |
        printf "%s\n" "${{ secrets.VPN_USERNAME }}" "${{ secrets.VPN_PASSWORD }}" > auth.txt
        chmod 600 auth.txt

    - name: Run OpenVPN
      run: |
        sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
        sleep 10

    - name: Verify VPN Connection
      run: |
        curl --max-time 10 https://ipinfo.io

    - name: Download and Process EPG Files
      run: |
        wget -O epg.xml.gz https://watch.livecricketsl.xyz/epg/epg.xml.gz
        gunzip -c epg.xml.gz > epg.xml
        mkdir -p public
        rm -f public/epg.xml*
        mv epg.xml.gz public/
        mv epg.xml public/

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .gitignore public/
        git commit -m "Update EPG files [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: |
        sudo pkill openvpn || true
        rm -f config.ovpn raw_config.ovpn auth.txt
