name: VPN File Download and Public Hosting

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 UTC (00:00 AKL, NZST)
  workflow_dispatch:

jobs:
  vpn-download-host:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenVPN and curl
      run: sudo apt-get update && sudo apt-get install -y openvpn curl

    - name: Decode and save OpenVPN configuration
      env:
        OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
      run: |
        echo "${OVPN_CONFIG}" | base64 -d > vpn-config.ovpn

    - name: Set up OpenVPN connection
      env:
        OVPN_USER: ${{ secrets.OVPN_USER }}
        OVPN_PASS: ${{ secrets.OVPN_PASS }}
      run: |
        # Debug secrets (optional, does not expose secret values)
        if [ -z "${OVPN_USER}" ]; then echo "OVPN_USER is empty"; exit 1; fi
        if [ -z "${OVPN_PASS}" ]; then echo "OVPN_PASS is empty"; exit 1; fi

        # Create auth.txt with username and password
        printf "%s\n%s" "${OVPN_USER}" "${OVPN_PASS}" > auth.txt

        # Start OpenVPN
        sudo openvpn --config vpn-config.ovpn --auth-user-pass auth.txt --daemon
        sleep 10 # Wait for the VPN connection to establish

    - name: Check VPN country
      run: |
        echo "Checking VPN country..."
        curl -s https://ipinfo.io | grep country || echo "Failed to retrieve country"

    - name: Test VPN connectivity
      run: |
        echo "Testing VPN connectivity..."
        ping -c 4 8.8.8.8 || { echo "VPN connection failed"; exit 1; }

    - name: Download the XML file
      run: |
        wget -O epg.xml.gz https://watch.livecricketsl.xyz/epg/epg.xml.gz
        mkdir -p public
        mv epg.xml.gz public/epg.xml.gz

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add public/epg.xml.gz
        git commit -m "Add updated epg.xml.gz"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
