name: VPN Connect and File Host

on:
  schedule:
    # Runs at 00:05 Auckland time (UTC+12 or UTC+13)
    - cron: '05 11,12 * * *'  # Triggers at both 11:05 and 12:05 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  vpn-download-host:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important for git history operations

    - name: Decode and Save OVPN Config
      run: |
        echo "${{ secrets.OVPN_FILE }}" | base64 -d > raw_config.ovpn
        fold -w 64 raw_config.ovpn > config.ovpn

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn

    - name: Create Auth File
      run: |
        printf "%s\n" "${{ secrets.VPN_USERNAME }}" "${{ secrets.VPN_PASSWORD }}" > auth.txt
        chmod 600 auth.txt

    - name: Run OpenVPN
      run: |
        sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
        sleep 10

    - name: Verify VPN Connection
      run: |
        curl --max-time 10 https://ipinfo.io

    - name: Download XML File
      run: |
        wget -O epg.xml.gz https://watch.livecricketsl.xyz/epg/epg.xml.gz
        gunzip -c epg.xml.gz > epg.xml

    - name: Prepare Public Directory
      run: |
        mkdir -p public
        # Force remove existing files if they exist
        rm -f public/epg.xml* || true

    - name: Move New Files
      run: |
        mv epg.xml.gz public/
        mv epg.xml public/

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add public/
        git commit -m "Update EPG files [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up VPN connection
      run: |
        sudo pkill openvpn || true
