name: VPN Debug Workflow

on:
  workflow_dispatch:

jobs:
  debug-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Decode and Save OVPN Config
      run: |
        echo "${{ secrets.OVPN_FILE }}" | base64 -d > raw_config.ovpn
        fold -w 64 raw_config.ovpn > config.ovpn
        wc -L config.ovpn
        cat config.ovpn

    - name: Install OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn
        sudo openvpn --version

    - name: Set up VPN
      run: |
        echo -e "${{ secrets.VPN_USERNAME}}\n${{ secrets.VPN_PASSWORD}}" > auth.txt
        sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
        sleep 10

    - name: Check VPN Status
      run: |
        sudo systemctl status openvpn

    - name: Verify VPN Connection
      run: |
        ip a
        curl --max-time 10 https://ipinfo.io

    - name: Debug OpenVPN Logs
      run: |
        sudo cat /var/log/syslog | grep openvpn
