name: VPN File Download and Public Hosting

on:
  workflow_dispatch:

jobs:
  vpn-download-host:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: Debug secrets
      env:
        OVPN_USER: ${{ secrets.OVPN_USER }}
        OVPN_PASS: ${{ secrets.OVPN_PASS }}
      run: |
        if [ -z "${OVPN_USER}" ]; then echo "Error: OVPN_USER is not set"; exit 1; fi
        if [ -z "${OVPN_PASS}" ]; then echo "Error: OVPN_PASS is not set"; exit 1; fi
        echo "OVPN_USER and OVPN_PASS are set correctly."

    - name: Set up OpenVPN connection
      env:
        OVPN_USER: ${{ secrets.OVPN_USER }}
        OVPN_PASS: ${{ secrets.OVPN_PASS }}
      run: |
        mkdir -p /tmp/vpn
        cd /tmp/vpn
        printf "%s\n%s" "${OVPN_USER}" "${OVPN_PASS}" > auth.txt
        chmod 600 auth.txt
        sudo openvpn --config /path/to/your-vpn-config.ovpn --auth-user-pass auth.txt --daemon
        sleep 10
