name: VPN File Download and Public Hosting

on:
  workflow_dispatch:

jobs:
  vpn-download-host:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenVPN
      run: sudo apt-get update && sudo apt-get install -y openvpn

    - name: Decode and save sensitive keys
      env:
        OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
      run: |
        mkdir -p /tmp/vpn
        echo "${OVPN_CONFIG}" | base64 -d > /tmp/vpn/vpn-config.ovpn

    - name: Verify VPN Configuration File
      run: |
        if [ ! -f /tmp/vpn/vpn-config.ovpn ]; then
          echo "Error: VPN configuration file not found at /tmp/vpn/vpn-config.ovpn"
          exit 1
        fi
        echo "VPN configuration file exists."

    - name: Set up OpenVPN connection
      env:
        OVPN_USER: ${{ secrets.OVPN_USER }}
        OVPN_PASS: ${{ secrets.OVPN_PASS }}
      run: |
        printf "%s\n%s" "${OVPN_USER}" "${OVPN_PASS}" > /tmp/vpn/auth.txt
        chmod 600 /tmp/vpn/auth.txt
        sudo openvpn --config /tmp/vpn/vpn-config.ovpn --auth-user-pass /tmp/vpn/auth.txt --daemon
        sleep 10

    - name: Check VPN country
      run: |
        echo "Checking VPN country..."
        curl -s https://ipinfo.io | grep country || echo "Failed to retrieve country"

    - name: Test VPN connectivity
      run: |
        echo "Testing VPN connectivity..."
        ping -c 4 8.8.8.8 || { echo "VPN connection failed"; exit 1; }
